pipeline {
    agent any
    stages {
        stage('Check Python Version') {
            steps {
                sh '''
                apt-get -y update
                apt-get -y upgrade --fix-missing
                apt-get install -y python3 python3-venv python3-pip
                pip --version
                pip install pytest

                '''

                sh 'python3 --version'
            }
        }
        stage('Create Virtual Environment') {
            steps {
                sh 'python3 -m venv venv'
            }
        }
        stage('Activate Virtual Environment and Install Packages') {
            steps {
                sh '''
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest 
                '''
            }
        }
    }
}