name: demo_project
on:
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      name: Virat
      shell: bash
      run: |
        echo "job1"
        sleep 25


  job2:
    runs-on: ubuntu-latest
    steps:
      name: Shri
      shell: bash
      run: |
        echo "job2"
        sleep 50


  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      name: Subha
      shell: bash
      run: |
        echo "job3"
        sleep 10